# 📘 Day 1 — NumPy Fundamentals

**Roadmap:** What is NumPy → Creating Arrays → Attributes → Indexing & Slicing → Basic Operations → `np.random` → Statistics → ✍️ Hands-on 01

## 1️⃣ What is NumPy?

> **Flow:** lists vs arrays (speed, memory) → `ndarray` → the idea of vectorization → Pandas/Sklearn are built on top of NumPy → import as `np`

In [1]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip


In [2]:
import numpy as np


## 2️⃣ Creating Arrays

> **Flow:** `np.array()` 1D & 2D → `zeros` / `ones` / `full` → `arange` (stop excluded) vs `linspace` (stop included) → `eye` → `dtype`

In [10]:
# np.array() — 1D and 2D

x=np.array([2,3,4,5])
x1=np.array([[2,3],[4,5],[8,9]])
print(x.dtype)
print(type(x))
print(x1)

int64
<class 'numpy.ndarray'>
[[2 3]
 [4 5]
 [8 9]]


In [16]:
# np.zeros(), np.ones(), np.full()
# print(np.zeros(20))
# print(np.zeros(10,dtype='int32'))
# print(np.zeros((3,4),dtype='int16'))
# print(np.ones(10))
# print(np.ones((3,4)))

print(np.full((4,3),15))

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [ ]:
# np.arange(start, stop, step)
print(np.arange(10,5,-2))
print(np.arange(10))


[10  8  6]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.arange(1,13).reshape(4,3))

ValueError: cannot reshape array of size 6 into shape (4,3)

In [25]:
# np.linspace(start, stop, num)

# print(np.linspace(1,10,5))
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# np.eye(n)
# print(np.eye(3,4))
print(np.eye(3,4,k=2)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


## 3️⃣ Array Attributes

> **Flow:** `shape` → `ndim` → `size` → `dtype` — (key point: most ML bugs are shape bugs)

In [33]:
arr=np.arange(5)
arr.shape

(5,)

In [39]:
# .shape, .ndim, .size, .dtype
x=np.arange(20).reshape(4,5)
# print(x)
# print(x.shape)

# print(arr.ndim)
# print(x.ndim)

# print(arr.size)
# print(x.size)
print(len(arr))
print(len(x))
print(type(arr))
print(arr.dtype)

5
4
<class 'numpy.ndarray'>
int64


---
## 🧠 Practice Set 1 — Array Creation

1. Create a 1D array containing numbers from **1 to 10**.
2. Create a **3×3 matrix of all zeros**, and another of **all ones**.
3. Create an array of all **even numbers between 2 and 20** (inclusive) using `np.arange`.
4. Create **5 equally spaced values between 0 and 1** using `np.linspace`.
5. Create a **4×4 identity matrix** and print its `shape`, `size`, and `ndim`.
6. Create a 1D array of numbers 1–5 with dtype `float` — observe the output.

In [ ]:
# Q1


In [ ]:
# Q2


In [ ]:
# Q3


In [ ]:
# Q4


In [ ]:
# Q5


In [ ]:
# Q6


## 4️⃣ Indexing & Slicing

> **Flow:** 1D indexing (positive + negative) → slicing `[start:stop:step]` → reverse trick `[::-1]` → 2D `[row, col]` (row / column / block) → boolean indexing `arr[arr > 50]` (the foundation of Pandas filtering)

In [42]:
# 1D indexing — positive and negative
arr=np.arange(10)
print(arr)
print(arr[-3:-12:-2])


[0 1 2 3 4 5 6 7 8 9]
[7 5 3 1]


In [ ]:
# 1D slicing — [start:stop:step], reverse


In [46]:
# 2D indexing — arr[row, col], full row, full column

arr=np.arange(20).reshape(5,4)
print(arr)
print(arr[2,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [51]:
# 2D slicing — sub-matrix (block)
print(arr)
# print(arr[2:,1:])
# print(arr[1,1:])

# print(arr[::4,::3])
print(arr[1:3,2::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 6  5  4]
 [10  9  8]]


In [ ]:
# Boolean indexing — arr[condition]


---
## 🧠 Practice Set 2 — Indexing & Slicing

1. Create an array of numbers **1 to 20**. Extract elements from **index 5 to 15**.
2. From the same array, extract **every alternate element**.
3. **Reverse** the array using slicing only.
4. From this matrix, extract: the **2nd row**, the **3rd column**, and the **middle 2×2 block**.
   ```python
   m = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12],
                 [13, 14, 15, 16]])
   ```
5. Given marks `[45, 82, 67, 33, 91, 58, 76]`, extract all marks **greater than 60**.

In [ ]:
# Q1


In [ ]:
# Q2


In [ ]:
# Q3


In [ ]:
# Q4


In [ ]:
# Q5


## 5️⃣ Basic Operations (Element-wise)

> **Flow:** array + scalar → array + array → `+ - * / **` → comparison operators → boolean array → (teaser: loops vs NumPy speed test coming on Day 2)

In [ ]:
# arithmetic — array with scalar, array with array


In [ ]:
# comparison operators — boolean arrays


## 6️⃣ The `np.random` Module

> **Flow:** `seed` (why reproducibility matters) → `rand` → `randn` → `randint` (high excluded) → `choice` → `shuffle`

In [ ]:
# np.random.seed() + np.random.rand()


In [ ]:
# np.random.randint(low, high, size)


In [ ]:
# np.random.choice(), np.random.shuffle()


## 7️⃣ Basic Statistics

> **Flow:** `min` / `max` / `sum` / `mean` / `median` / `std` / `var` → `argmax` vs `max` (the topper's marks vs the topper's index) → **`axis`**: `axis=0` column-wise ↓, `axis=1` row-wise →

In [ ]:
# min, max, sum, mean, median, std


In [ ]:
# argmin / argmax


In [ ]:
# axis=0 vs axis=1 on a 2D array


---
## 🧠 Practice Set 3 — Random & Statistics

1. Set `seed = 42` and simulate **10 dice rolls** (values 1–6) using `randint`.
2. Generate **20 random marks** between 35 and 100. Find the **mean, max, min, and std**.
3. Create a **3×4 random integer matrix** (values 10–50). Find the **column-wise mean** and **row-wise sum**.
4. In the marks array from Q2, find the **index of the topper**.
5. Using `np.random.choice`, randomly select **3 students** from `['Aman', 'Priya', 'Rahul', 'Sneha', 'Vikram']`.

In [ ]:
# Q1


In [ ]:
# Q2


In [ ]:
# Q3


In [ ]:
# Q4


In [ ]:
# Q5


---
# ✍️ Hands-on 01 — Array Creation & Basic Operations

⏱️ *~15 minutes. Solve independently using only today's concepts.*

### Part A — Warm-up
1. Create a 1D array of the **first 10 multiples of 5** (5, 10, ..., 50).
2. Create a **5×5 matrix** where every element is **7**.
3. Create **8 equally spaced values between 0 and 100**.

### Part B — Scenario: Class Test Marks 📊
A class of **15 students** gave a test (marks out of 100).

4. Set `seed = 10` and generate the 15 marks using `randint` (range 30–100).
5. Find the **average, highest, lowest, and standard deviation** of the class.
6. **How many students scored above 75?** *(Hint: boolean array + `.sum()`)*
7. Extract the marks of the **first 5 students** and the **last 3 students** (negative slicing).
8. Give **5 grace marks to everyone** — in one line, no loop!
9. Find the **roll number (index) of the topper**.

### Part C — Challenge 🚀
10. `prices = [120, 250, 90, 400, 60]`, `quantities = [2, 1, 5, 1, 3]` → compute the **total bill** in one line.
11. **(Brain teaser)** Create an **8×8 chessboard pattern** of 0s and 1s using `np.zeros` + step slicing.

In [ ]:
# Part A — Q1


In [ ]:
# Part A — Q2


In [ ]:
# Part A — Q3


In [ ]:
# Part B — Q4


In [ ]:
# Part B — Q5


In [ ]:
# Part B — Q6


In [ ]:
# Part B — Q7


In [ ]:
# Part B — Q8


In [ ]:
# Part B — Q9


In [ ]:
# Part C — Q10


In [ ]:
# Part C — Q11


---
## 📌 Recap: `array/zeros/ones/full/arange/linspace/eye` · `shape/ndim/size/dtype` · indexing/slicing/boolean · element-wise ops · `random` · stats + `axis`

**🔜 Day 2:** loops vs vectorization (`%timeit`) · `reshape/flatten/newaxis` · stacking · `np.where` · dot product & matmul